/**
 * 同人角色库（fan art character library）
 * ------------------------------------------------------------------
 * 为什么需要它：SD 模型对「原作品角色」的还原，靠的是 **booru 角色 tag**
 * （`hu tao (genshin impact)`）+ 该角色的标志性特征 tag。只写中文名或只写几个特征，
 * 出来的只是「一个像她的原创角色」；写对了 booru tag，模型才会真的调出原作的那张脸。
 *
 * 每条字段：
 *   id         英文唯一键（内部用，改了会断引用）
 *   zh / en / jp  中/英/日文名
 *   series     作品中文名        seriesTag  作品的 booru tag（如 `genshin impact`）
 *   booru      角色 booru tag（最重要的一格）
 *   rating     sfw | nsfw | galgame  （面板可按这个过滤）
 *   aliases    别名/外号/简称 —— 正文里的人名匹配靠这个（中文外号一定要写全）
 *   identity   外观 tag：发色/发型/瞳色/体型/标志物。**不含服装**
 *   outfitName 标志性服装在服装库里的名字（会自动建档，可随时改）
 *   outfit     标志性服装 tag
 *   note       一句话说明（辨识点，给自己看的）
 *
 * 数据是「我写 + safebooru 共现标签统计校对」出来的：校对方法是抓该角色 100 张图，
 * 统计 co-occur 最高的特征 tag，所以发色/瞳色/标志物这些不容易写错。
 * 想加角色：照抄一条改内容即可；想加整个系列，新开一个数组追加进去。
 */

export const FANCHARS = [
    {
        id: 'hu_tao', zh: '胡桃', en: 'Hu Tao', jp: '胡桃', series: '原神', seriesTag: 'genshin impact',
        booru: 'hu tao (genshin impact)', rating: 'sfw',
        aliases: ['胡桃', 'hutao', 'hu tao', '往生堂', '堂主', '胡堂主', '第七十七代堂主'],
        identity: 'long brown hair, twintails, flower-shaped pupils, red eyes, ahoge, hair between eyes, pale skin, flat chest, youthful',
        outfitName: '标志性服装·胡桃',
        outfit: 'black wide-brimmed hat, hat flower, plum blossom print, black jacket, red trim, long sleeves, white shirt, black shorts, black thighhighs, brown boots, talisman, multiple rings, black nails, chinese clothes',
        note: '往生堂七十七代堂主。黑帽+红梅+黑指甲+一堆戒指，缺一个都不像她。',
    },
    {
        id: 'ganyu', zh: '甘雨', en: 'Ganyu', jp: '甘雨', series: '原神', seriesTag: 'genshin impact',
        booru: 'ganyu (genshin impact)', rating: 'sfw',
        aliases: ['甘雨', 'ganyu', '椰羊', '半仙', '月海亭'],
        identity: 'blue hair, long hair, goat horns, violet eyes, ahoge, sidelocks, hair between eyes, bare shoulders, medium breasts',
        outfitName: '标志性服装·甘雨',
        outfit: 'white dress, detached sleeves, white sleeves, black gloves, neck bell, gold trim, blue bodysuit, pantyhose, chinese clothes, jewelry, bow',
        note: '麒麟混血。角+颈铃+黑色手套+分体袖；发色是蓝不是绿。',
    },
    {
        id: 'raiden_shogun', zh: '雷电将军', en: 'Raiden Shogun', jp: '雷電将軍', series: '原神', seriesTag: 'genshin impact',
        booru: 'raiden shogun', rating: 'sfw',
        aliases: ['雷电将军', '雷神', '影', 'raiden', 'raidenshogun', 'raiden shogun', '巴尔泽布', '将军'],
        identity: 'purple hair, very long hair, violet eyes, mole under eye, braid, blunt bangs, hair ornament, purple hair flower, pale skin',
        outfitName: '标志性服装·雷电将军',
        outfit: 'purple kimono, japanese clothes, bridal gauntlets, sash, shoulder cutout, hair flower, thighhighs, sandals, long sleeves, hair ornament',
        note: '眼下的痣是辨识点。紫和服+白臂甲（bridal gauntlets）。',
    },
    {
        id: 'yae_miko', zh: '八重神子', en: 'Yae Miko', jp: '八重神子', series: '原神', seriesTag: 'genshin impact',
        booru: 'yae miko', rating: 'sfw',
        aliases: ['八重神子', '八重', '神子', 'yae miko', 'yaemiko', 'yae', '屑狐狸', '宫司'],
        identity: 'pink hair, long hair, fox ears, animal ears, violet eyes, hair between eyes, braid, hair ornament, bare shoulders',
        outfitName: '标志性服装·八重神子',
        outfit: 'white top, red hakama, japanese clothes, detached sleeves, wide sleeves, hair ornament, jewelry, earrings, thighhighs, sandals',
        note: '粉发+狐耳+紫瞳；红白巫女系配色。',
    },
    {
        id: 'kamisato_ayaka', zh: '神里绫华', en: 'Kamisato Ayaka', jp: '神里綾華', series: '原神', seriesTag: 'genshin impact',
        booru: 'kamisato ayaka', rating: 'sfw',
        aliases: ['神里绫华', '绫华', '神里', 'ayaka', 'kamisato ayaka', 'kamisatoayaka', '白鹭公主'],
        identity: 'blue hair, long hair, blue eyes, mole under eye, ponytail, blunt bangs, blunt tresses, hair ornament, pale skin',
        outfitName: '标志性服装·神里绫华',
        outfit: 'blue dress, white dress, hair ribbon, tassel, black gloves, armor plating, thighhighs, japanese clothes, ribbon, bow',
        note: '有 ponytail（高马尾）和眼下痣；蓝白和风礼服+蓝蝴蝶结。',
    },
    {
        id: 'yoimiya', zh: '宵宫', en: 'Yoimiya', jp: '宵宮', series: '原神', seriesTag: 'genshin impact',
        booru: 'yoimiya (genshin impact)', rating: 'sfw',
        aliases: ['宵宫', 'yoimiya', '长野原', '烟花店'],
        identity: 'blonde hair, long hair, orange eyes, ponytail, hair between eyes, hair ornament, tattoo, bandages',
        outfitName: '标志性服装·宵宫',
        outfit: 'orange kimono, japanese clothes, long sleeves, hair ribbon, choker, bandaged arm, sarashi, hair ornament, gloves, jewelry',
        note: '金发+橙瞳+马尾；橙和服、手臂绷带和纹身。',
    },
    {
        id: 'sangonomiya_kokomi', zh: '珊瑚宫心海', en: 'Sangonomiya Kokomi', jp: '珊瑚宮心海', series: '原神', seriesTag: 'genshin impact',
        booru: 'sangonomiya kokomi', rating: 'sfw',
        aliases: ['心海', '珊瑚宫心海', 'kokomi', 'sangonomiya kokomi', 'sangonomiyakokomi', '现人神巫女'],
        identity: 'pink hair, gradient hair, multicolored hair, very long hair, violet eyes, bow-shaped hair, bare shoulders',
        outfitName: '标志性服装·心海',
        outfit: 'white dress, purple dress, detached sleeves, white gloves, coral hair ornament, pearl hair ornament, frills, thighhighs, japanese clothes, bow',
        note: '粉→蓝渐变长发+弓形发髻；珊瑚与珍珠发饰。',
    },
    {
        id: 'keqing', zh: '刻晴', en: 'Keqing', jp: '刻晴', series: '原神', seriesTag: 'genshin impact',
        booru: 'keqing (genshin impact)', rating: 'sfw',
        aliases: ['刻晴', 'keqing', '玉衡星', '璃月七星'],
        identity: 'purple hair, long hair, cone hair bun, double bun, twintails, violet eyes, hair between eyes, bare shoulders, pale skin',
        outfitName: '标志性服装·刻晴',
        outfit: 'purple dress, detached sleeves, purple gloves, pantyhose, hair flower, gold trim, frills, sandals, chinese clothes',
        note: '标志是那两个锥形发髻（cone hair bun），不是猫耳。紫裙+紫手套+黑丝。',
    },
    {
        id: 'mona', zh: '莫娜', en: 'Mona', jp: 'モナ', series: '原神', seriesTag: 'genshin impact',
        booru: 'mona (genshin impact)', rating: 'sfw',
        aliases: ['莫娜', 'mona', '阿斯托洛吉斯', '占星术士', '水占'],
        identity: 'black hair, twintails, long hair, aqua eyes, blunt ends, sidelocks, asymmetrical bangs, tsurime, star-shaped pupils',
        outfitName: '标志性服装·莫娜',
        outfit: 'black witch hat, blue leotard, detached sleeves, black gloves, star earrings, choker, cape, thighhighs, star symbol, jewelry',
        note: '双马尾+星形瞳孔+溺水蓝；黑女巫帽和紧身衣是核心。',
    },
    {
        id: 'furina', zh: '芙宁娜', en: 'Furina', jp: 'フリーナ', series: '原神', seriesTag: 'genshin impact',
        booru: 'furina (genshin impact)', rating: 'sfw',
        aliases: ['芙宁娜', '水神', 'furina', '芙卡洛斯', '审判官'],
        identity: 'white hair, streaked hair, blue hair, long hair, heterochromia, drop-shaped pupils, ahoge, hair between eyes, pale skin',
        outfitName: '标志性服装·芙宁娜',
        outfit: 'blue top hat, blue jacket, white shirt, ascot, shorts, white gloves, black gloves, gem, blue gem, top hat, long sleeves',
        note: '白发挑蓝+异色瞳+水滴形瞳；蓝色高礼帽、领巾、短裤。',
    },
    {
        id: 'shiroko', zh: '白子', en: 'Shiroko', jp: 'シロコ', series: '蔚蓝档案', seriesTag: 'blue archive',
        booru: 'shiroko (blue archive)', rating: 'sfw',
        aliases: ['白子', 'shiroko', '砂狼白子', '对策委员会'],
        identity: 'grey hair, wolf ears, animal ears, animal ear fluff, blue eyes, blue halo, cross hair ornament, medium hair',
        outfitName: '标志性服装·白子',
        outfit: 'white shirt, blue scarf, necktie, black jacket, pleated skirt, long sleeves, school uniform, fingerless gloves',
        note: '灰发+狼耳+头顶十字发饰+蓝色光环；蓝色围巾是重点。',
    },
    {
        id: 'azusa', zh: '梓', en: 'Azusa', jp: 'アズサ', series: '蔚蓝档案', seriesTag: 'blue archive',
        booru: 'azusa (blue archive)', rating: 'sfw',
        aliases: ['梓', 'azusa', '白洲梓', '阿梓'],
        identity: 'white hair, long hair, violet eyes, yellow halo, crossed bangs, hair between eyes, purple hair flower, white wings, feathered wings',
        outfitName: '标志性服装·梓',
        outfit: 'white shirt, black dress, sailor collar, frills, long sleeves, hair flower, purple flower, shoes, school uniform',
        note: '白发+紫瞳+黄光环+背后的白色羽翼（低位）。紫花发饰。',
    },
    {
        id: 'asuna', zh: '明日奈', en: 'Asuna', jp: 'アスナ', series: '蔚蓝档案', seriesTag: 'blue archive',
        booru: 'asuna (blue archive)', rating: 'sfw',
        aliases: ['明日奈', 'asuna', '一之濑明日奈', '一之瀬アスナ'],
        identity: 'blonde hair, very long hair, blue eyes, hair over one eye, blue halo, large breasts, grin',
        outfitName: '标志性服装·明日奈',
        outfit: 'white shirt, blue bow, bowtie, ribbon, pleated skirt, choker, school uniform, long sleeves',
        note: '金发+蓝瞳+盖住一只眼的刘海+蓝光环；白衬衫蓝领结。',
    },
    {
        id: 'koharu', zh: '小春', en: 'Koharu', jp: 'コハル', series: '蔚蓝档案', seriesTag: 'blue archive',
        booru: 'koharu (blue archive)', rating: 'sfw',
        aliases: ['小春', 'koharu', '下江小春', '补课部'],
        identity: 'pink hair, twintails, long hair, pink eyes, pink halo, head wings, black wings, feathered wings, blush',
        outfitName: '标志性服装·小春',
        outfit: 'black beret, black shirt, white sailor collar, pink neckerchief, pleated skirt, long sleeves, school uniform, low wings',
        note: '粉发双马尾+头顶黑色小翅膀+粉光环；黑贝雷帽、白水手领、粉领巾。',
    },
    {
        id: 'kayoko', zh: '佳代子', en: 'Kayoko', jp: 'カヨコ', series: '蔚蓝档案', seriesTag: 'blue archive',
        booru: 'kayoko (blue archive)', rating: 'sfw',
        aliases: ['佳代子', 'kayoko', '鬼方佳代子', '便利屋68'],
        identity: 'black hair, two-tone hair, white hair, long hair, red eyes, black horns, demon horns, grey halo, ear piercing, ponytail',
        outfitName: '标志性服装·佳代子',
        outfit: 'black hoodie, hood, black choker, long sleeves, skirt, school uniform, piercing, single wing',
        note: '黑白双色发+红瞳+黑角+灰光环+耳钉；黑色连帽卫衣。',
    },
    {
        id: 'hina', zh: '日奈', en: 'Hina', jp: 'ヒナ', series: '蔚蓝档案', seriesTag: 'blue archive',
        booru: 'hina (blue archive)', rating: 'sfw',
        aliases: ['日奈', 'hina', '空崎日奈', '风纪委员会'],
        identity: 'white hair, grey hair, very long hair, violet eyes, demon horns, multiple horns, black halo, ahoge, parted bangs, hairclip',
        outfitName: '标志性服装·日奈',
        outfit: 'black dress, gloves, long sleeves, school uniform, hairclip, demon wings, thighhighs',
        note: '白发紫瞳+黑色多角+黑光环+大呆毛；黑色制服裙。',
    },
    {
        id: 'arona', zh: '阿罗娜', en: 'Arona', jp: 'アロナ', series: '蔚蓝档案', seriesTag: 'blue archive',
        booru: 'arona (blue archive)', rating: 'sfw',
        aliases: ['阿罗娜', 'arona', '普拉娜', '主控AI'],
        identity: 'blue hair, multicolored hair, colored inner hair, pink inner hair, single braid, hair over one eye, blue eyes, blue halo, short hair',
        outfitName: '标志性服装·阿罗娜',
        outfit: 'blue shirt, white sailor collar, white hairband, bow hairband, white skirt, choker, long sleeves, school uniform, bow',
        note: '蓝发带粉色内层+单侧麻花辫+蓝光环；白发箍蝴蝶结、白水手领。',
    },
    {
        id: 'yuuka', zh: '优香', en: 'Yuuka', jp: 'ユウカ', series: '蔚蓝档案', seriesTag: 'blue archive',
        booru: 'yuuka (blue archive)', rating: 'sfw',
        aliases: ['优香', 'yuuka', '早濑优香', '研讨会'],
        identity: 'purple hair, long hair, two side up, blue eyes, violet eyes, black halo, mechanical halo, hair between eyes',
        outfitName: '标志性服装·优香',
        outfit: 'white shirt, blue necktie, white jacket, black skirt, pleated skirt, collared shirt, black gloves, long sleeves, school uniform',
        note: '紫发两侧束起+机械感黑光环；白衬衫蓝领带白外套。',
    },
    {
        id: 'mika', zh: '未花', en: 'Mika', jp: 'ミカ', series: '蔚蓝档案', seriesTag: 'blue archive',
        booru: 'mika (blue archive)', rating: 'sfw',
        aliases: ['未花', 'mika', '圣园未花', '茶话会'],
        identity: 'pink hair, long hair, yellow eyes, pink halo, single side bun, hair bun, white wings, low wings, feathered wings',
        outfitName: '标志性服装·未花',
        outfit: 'white dress, white capelet, blue bow, hair flower, bow, scrunchie, frills, thighhighs',
        note: '粉发侧丸子头+黄瞳+粉光环+低垂白羽翼；白裙白披肩+蓝蝴蝶结。',
    },
    {
        id: 'hoshino', zh: '星野', en: 'Hoshino', jp: 'ホシノ', series: '蔚蓝档案', seriesTag: 'blue archive',
        booru: 'hoshino (blue archive)', rating: 'sfw',
        aliases: ['星野', 'hoshino', '小鸟游星野', '对策委员会'],
        identity: 'pink hair, long hair, heterochromia, blue eyes, yellow eyes, huge ahoge, pink halo, hair between eyes, fang',
        outfitName: '标志性服装·星野',
        outfit: 'white shirt, blue necktie, collared shirt, pleated skirt, long sleeves, school uniform, gloves',
        note: '粉发+异色瞳（蓝/黄）+超长呆毛+粉光环+虎牙。',
    },
    {
        id: 'arisu', zh: '爱丽丝', en: 'Arisu', jp: 'アリス', series: '蔚蓝档案', seriesTag: 'blue archive',
        booru: 'arisu (blue archive)', rating: 'sfw',
        aliases: ['爱丽丝', 'arisu', '天童爱丽丝', '游戏开发部'],
        identity: 'black hair, blue hair, very long hair, blue eyes, blue halo, one side up, hair between eyes',
        outfitName: '标志性服装·爱丽丝',
        outfit: 'white shirt, blue necktie, black jacket, black skirt, pleated skirt, collared shirt, black hairband, school uniform',
        note: '黑发（挑蓝）+蓝瞳+蓝光环+黑发箍+单侧束发。',
    },
    {
        id: 'amiya', zh: '阿米娅', en: 'Amiya', jp: 'アーミヤ', series: '明日方舟', seriesTag: 'arknights',
        booru: 'amiya (arknights)', rating: 'sfw',
        aliases: ['阿米娅', 'amiya', '兔兔', '小兔', '罗德岛领袖'],
        identity: 'brown hair, long hair, rabbit ears, animal ears, animal ear fluff, blue eyes, hair between eyes, ponytail',
        outfitName: '标志性服装·阿米娅',
        outfit: 'black jacket, white dress, white shirt, ascot, skirt, pantyhose, multiple rings, jewelry, long sleeves',
        note: '棕发+兔耳+蓝瞳；黑外套白裙+一手的戒指。',
    },
    {
        id: 'kaltsit', zh: '凯尔希', en: "Kal'tsit", jp: 'ケルシー', series: '明日方舟', seriesTag: 'arknights',
        booru: "kal'tsit (arknights)", rating: 'sfw',
        aliases: ['凯尔希', 'kaltsit', "kal'tsit", '凯太后', '凯医生'],
        identity: 'green hair, grey hair, long hair, green eyes, cat ears, animal ears, animal ear fluff, bare shoulders',
        outfitName: '标志性服装·凯尔希',
        outfit: 'green dress, off shoulder, white dress, black jacket, long sleeves, coat, thighhighs',
        note: '绿发猫耳+绿瞳+露肩绿裙；身边常有 Mon3tr。',
    },
    {
        id: 'skadi', zh: '斯卡蒂', en: 'Skadi', jp: 'スカジ', series: '明日方舟', seriesTag: 'arknights',
        booru: 'skadi (arknights)', rating: 'sfw',
        aliases: ['斯卡蒂', 'skadi', '蒂蒂', '深海猎人'],
        identity: 'grey hair, very long hair, red eyes, hair between eyes, bare shoulders, pale skin, tall',
        outfitName: '标志性服装·斯卡蒂',
        outfit: 'black hat, aqua hat, red dress, black ascot, black gloves, detached sleeves, clothing cutout, long sleeves, thighhighs',
        note: '灰发红瞳+黑青色帽子+红裙+黑领巾；高个子。',
    },
    {
        id: 'surtr', zh: '史尔特尔', en: 'Surtr', jp: 'スルト', series: '明日方舟', seriesTag: 'arknights',
        booru: 'surtr (arknights)', rating: 'sfw',
        aliases: ['史尔特尔', 'surtr', '42', '四二', '火巨人'],
        identity: 'red hair, long hair, violet eyes, demon horns, black horns, hair intakes, hair between eyes, bare shoulders',
        outfitName: '标志性服装·史尔特尔',
        outfit: 'black dress, white dress, gloves, black gloves, jewelry, long sleeves, thighhighs',
        note: '红发紫瞳+黑角+脸颊两侧的 hair intakes；黑白裙。',
    },
    {
        id: 'w', zh: 'W', en: 'W', jp: 'W', series: '明日方舟', seriesTag: 'arknights',
        booru: 'w (arknights)', rating: 'sfw',
        aliases: ['W', 'w', '大W', '萨卡兹佣兵'],
        identity: 'grey hair, streaked hair, red hair, short hair, antenna hair, orange eyes, demon horns, red horns, demon tail, red nails',
        outfitName: '标志性服装·W',
        outfit: 'black jacket, open jacket, white shirt, black skirt, fingerless gloves, black gloves, thighhighs, jewelry',
        note: '灰发挑红+橙瞳+红色恶魔角+呆毛天线+尾巴+红指甲。',
    },
    {
        id: 'texas', zh: '德克萨斯', en: 'Texas', jp: 'テキサス', series: '明日方舟', seriesTag: 'arknights',
        booru: 'texas (arknights)', rating: 'sfw',
        aliases: ['德克萨斯', 'texas', '德狗', '企鹅物流'],
        identity: 'black hair, long hair, wolf ears, animal ears, animal ear fluff, orange eyes, wolf tail, hair between eyes',
        outfitName: '标志性服装·德州',
        outfit: 'white shirt, black vest, black jacket, necktie, shorts, black pantyhose, blue gloves, fingerless gloves, collared shirt',
        note: '黑发狼耳+橙瞳+黑尾；白衬衫黑马甲黑领带+黑丝短裤。',
    },
    {
        id: 'exusiai', zh: '能天使', en: 'Exusiai', jp: 'エクシア', series: '明日方舟', seriesTag: 'arknights',
        booru: 'exusiai (arknights)', rating: 'sfw',
        aliases: ['能天使', 'exusiai', '小天使', '企鹅物流'],
        identity: 'red hair, short hair, one side up, yellow eyes, halo, traditional halo, detached wings, energy wings',
        outfitName: '标志性服装·能天使',
        outfit: 'black jacket, white shirt, fingerless gloves, black gloves, skirt, boots, jewelry',
        note: '红发+黄瞳+光环+背后分离式光翼；黑夹克白衬衫露指手套。',
    },
    {
        id: 'nearl', zh: '临光', en: 'Nearl', jp: 'ニアール', series: '明日方舟', seriesTag: 'arknights',
        booru: 'nearl (arknights)', rating: 'sfw',
        aliases: ['临光', 'nearl', '耀骑士', '玛嘉烈'],
        identity: 'blonde hair, long hair, horse ears, animal ears, animal ear fluff, yellow eyes, ponytail, horse tail, headset',
        outfitName: '标志性服装·临光',
        outfit: 'armor, shoulder armor, pauldrons, breastplate, dress, black gloves, holding weapon, tail',
        note: '金发马耳+黄瞳+马尾+马尾巴；铠甲肩甲是重点（耀骑士）。',
    },
    {
        id: 'goldenglow', zh: '澄闪', en: 'Goldenglow', jp: 'ゴールデングロー', series: '明日方舟', seriesTag: 'arknights',
        booru: 'goldenglow (arknights)', rating: 'sfw',
        aliases: ['澄闪', 'goldenglow', 'golden glow', '粉毛', '闪电'],
        identity: 'pink hair, long hair, cat ears, animal ears, floppy ears, yellow eyes, cat tail, braid, long hair',
        outfitName: '标志性服装·澄闪',
        outfit: 'black hairband, lightning bolt print, pink jacket, blue bow, white shirt, skirt, long sleeves, open jacket',
        note: '粉发猫耳（垂耳）+黄瞳+猫尾；带闪电印花的黑发箍和粉色外套。',
    },
    {
        id: 'ling', zh: '令', en: 'Ling', jp: 'リン', series: '明日方舟', seriesTag: 'arknights',
        booru: 'ling (arknights)', rating: 'sfw',
        aliases: ['令', 'ling', '龙王', '大炎', '酒仙'],
        identity: 'blue hair, streaked hair, black hair, long hair, blue eyes, dragon horns, eastern dragon horns, pointy ears, dragon tail, colored extremities',
        outfitName: '标志性服装·令',
        outfit: 'white shirt, black skirt, jewelry, earrings, long sleeves, thighhighs, sash',
        note: '蓝黑挑染长发+东方龙角+尖耳+龙尾+发梢变色；白衬衫。',
    },
    {
        id: 'yun_jin', zh: '云堇', en: 'Yun Jin', jp: '雲菫', series: '原神', seriesTag: 'genshin impact',
        booru: 'yun jin (genshin impact)', rating: 'sfw',
        aliases: ['云堇', '雲菫', 'yunjin', 'yun jin', '云先生', '和裕茶馆'],
        identity: 'black hair, purple hair, long hair, red eyes, blunt bangs, makeup, eyeshadow, hair ornament',
        outfitName: '标志性服装·云堇',
        outfit: 'pink capelet, bonnet, chinese clothes, long sleeves, tassel, dress, hat, lolita fashion, hair ornament',
        note: '唱戏的「云先生」。黑紫长发、红瞳、眼妆与粉色小披肩+软帽是辨识点。',
    },
    {
        id: 'xiangling', zh: '香菱', en: 'Xiangling', jp: '香菱', series: '原神', seriesTag: 'genshin impact',
        booru: 'xiangling (genshin impact)', rating: 'sfw',
        aliases: ['香菱', 'xiangling', '香菱大厨', '万民堂', '锅巴'],
        identity: 'brown hair, blue hair, short hair, braid, yellow eyes, hair rings, hair ornament, hair between eyes',
        outfitName: '标志性服装·香菱',
        outfit: 'chinese clothes, long sleeves, hat, gloves, jacket, dress, hair ornament',
        note: '带蓝色挑染的棕发+发环+黄瞳；中式短打与厨师帽。',
    },
    {
        id: 'eula', zh: '优菈', en: 'Eula', jp: 'エウルア', series: '原神', seriesTag: 'genshin impact',
        booru: 'eula (genshin impact)', rating: 'sfw',
        aliases: ['优菈', 'eula', '浪花骑士', '劳伦斯', '记仇'],
        identity: 'blue hair, medium hair, blond hair, yellow eyes, hair between eyes, hair ornament',
        outfitName: '标志性服装·优菈',
        outfit: 'black hairband, black gloves, blue necktie, long sleeves, hair ornament, boots, dress',
        note: '浅蓝（偏金）中长发+黄瞳；黑发箍、蓝领带、黑手套。',
    },
    {
        id: 'layla', zh: '莱依拉', en: 'Layla', jp: 'レイラ', series: '原神', seriesTag: 'genshin impact',
        booru: 'layla (genshin impact)', rating: 'sfw',
        aliases: ['莱依拉', 'layla', '明论派', '睡不醒'],
        identity: 'blue hair, long hair, drill hair, drill sidelocks, pointy ears, yellow eyes, bare shoulders, sidelocks',
        outfitName: '标志性服装·莱依拉',
        outfit: 'blue hood, hood up, detached sleeves, blue sleeves, black gloves, white pantyhose, dress, jewelry',
        note: '蓝色钻头（drill hair）双马尾+尖耳+黄瞳；蓝色兜帽与分体袖。',
    },
    {
        id: 'izuna', zh: '泉奈', en: 'Izuna', jp: 'イズナ', series: '蔚蓝档案', seriesTag: 'blue archive',
        booru: 'izuna (blue archive)', rating: 'sfw',
        aliases: ['泉奈', 'izuna', '久田泉奈', '忍者', '小狐狸'],
        identity: 'brown hair, short hair, fox ears, animal ears, animal ear fluff, fox tail, yellow eyes, fang, pink halo',
        outfitName: '标志性服装·泉奈',
        outfit: 'pink scarf, neckerchief, shirt, skirt, gloves, hair ornament, makeup',
        note: '狐耳+狐尾+粉光环+虎牙；粉色围巾是重点。',
    },
    {
        id: 'wakamo', zh: '若藻', en: 'Wakamo', jp: 'ワカモ', series: '蔚蓝档案', seriesTag: 'blue archive',
        booru: 'wakamo (blue archive)', rating: 'sfw',
        aliases: ['若藻', 'wakamo', '狐坂若藻', '狐狸', '灾厄'],
        identity: 'red hair, black hair, two-tone hair, colored inner hair, long hair, fox ears, animal ear fluff, fox tail, yellow eyes, red halo',
        outfitName: '标志性服装·若藻',
        outfit: 'kimono, japanese clothes, hair ornament, sash, thighhighs, sandals',
        note: '红黑双色长发+狐耳狐尾+红光环；和服造型。',
    },
    {
        id: 'hanako', zh: '花子', en: 'Hanako', jp: 'ハナコ', series: '蔚蓝档案', seriesTag: 'blue archive',
        booru: 'hanako (blue archive)', rating: 'sfw',
        aliases: ['花子', 'hanako', '浦和花子', '补课部', '小恶魔'],
        identity: 'pink hair, long hair, twintails, green eyes, pink halo, ahoge, head wings',
        outfitName: '标志性服装·花子',
        outfit: 'white shirt, sailor collar, serafuku, school uniform, bow, pleated skirt, long sleeves',
        note: '粉发双马尾+绿瞳+头顶小翅膀+粉光环；水手服。',
    },
    {
        id: 'ui', zh: '忧', en: 'Ui', jp: 'ウイ', series: '蔚蓝档案', seriesTag: 'blue archive',
        booru: 'ui (blue archive)', rating: 'sfw',
        aliases: ['忧', 'ui', '才羽忧', '游戏开发部', '书虫'],
        identity: 'black hair, purple hair, very long hair, violet eyes, crossed bangs, hair between eyes, brown halo',
        outfitName: '标志性服装·忧',
        outfit: 'brown cardigan, white sailor collar, serafuku, school uniform, neckerchief, purple hairband, necklace, jewelry',
        note: '黑紫超长发+紫瞳+棕光环；棕开衫、白水手领、紫发箍，常抱着书。',
    },
    {
        id: 'eyjafjalla', zh: '艾雅法拉', en: 'Eyjafjalla', jp: 'エイヤフィヤトラ', series: '明日方舟', seriesTag: 'arknights',
        booru: 'eyjafjalla (arknights)', rating: 'sfw',
        aliases: ['艾雅法拉', 'eyjafjalla', '小羊', '火山', 'エイヤ'],
        identity: 'brown hair, long hair, sheep horns, horns, animal ears, sheep ears, pink eyes, ahoge, animal ear fluff',
        outfitName: '标志性服装·艾雅法拉',
        outfit: 'white shirt, black thighhighs, gloves, bow, dress, long sleeves, bare shoulders',
        note: '羊角+羊耳+棕长发+粉瞳+呆毛；白衬衫黑丝。',
    },
    {
        id: 'ifrit', zh: '伊芙利特', en: 'Ifrit', jp: 'イフリータ', series: '明日方舟', seriesTag: 'arknights',
        booru: 'ifrit (arknights)', rating: 'sfw',
        aliases: ['伊芙利特', 'ifrit', '小火龙', '赫默', '塞雷娅'],
        identity: 'blonde hair, short twintails, twintails, orange eyes, demon horns, tail, demon girl, short hair',
        outfitName: '标志性服装·伊芙利特',
        outfit: 'black jacket, dress, long sleeves, boots, gloves, tail',
        note: '金发短双马尾+橙瞳+恶魔角与尾巴（小火龙）。',
    },
    {
        id: 'swire', zh: '诗怀雅', en: 'Swire', jp: 'スワイヤー', series: '明日方舟', seriesTag: 'arknights',
        booru: 'swire (arknights)', rating: 'sfw',
        aliases: ['诗怀雅', 'swire', '虎鲸', '龙门', '大小姐'],
        identity: 'blonde hair, long hair, drill hair, tiger ears, animal ears, tiger tail, green eyes, sidelocks, fang',
        outfitName: '标志性服装·诗怀雅',
        outfit: 'black hat, white shirt, green jacket, gloves, tail, jacket',
        note: '金发钻头卷+虎耳虎尾+绿瞳+虎牙；白衬衫绿外套加黑帽。',
    },
    {
        id: 'angelina', zh: '安洁莉娜', en: 'Angelina', jp: 'アンジェリーナ', series: '明日方舟', seriesTag: 'arknights',
        booru: 'angelina (arknights)', rating: 'sfw',
        aliases: ['安洁莉娜', 'angelina', '安洁', '小狐狸', '信使'],
        identity: 'brown hair, long hair, twintails, fox ears, animal ears, animal ear fluff, hair between eyes',
        outfitName: '标志性服装·安洁莉娜',
        outfit: 'white dress, black collar, black hairband, long sleeves, black gloves, detached sleeves, gloves',
        note: '棕发双马尾+狐耳+黑发箍+黑项圈+白裙。',
    },
    {
        id: 'march_7th', zh: '三月七', en: 'March 7th', jp: '三月なのか', series: '崩坏：星穹铁道', seriesTag: 'honkai: star rail',
        booru: 'march 7th (honkai: star rail)', rating: 'sfw',
        aliases: ['三月七', 'march 7th', 'march7th', '小三月', '三月'],
        identity: 'pink hair, long hair, multicolored eyes, heterochromia, red eyes, blue eyes, hair between eyes, hair flower',
        outfitName: '标志性服装·三月七',
        outfit: 'white shirt, black gloves, blue jacket, hair flower, earrings, long sleeves, dress, jewelry',
        note: '粉长发+异色瞳（红/蓝）+发花；白衬衫、黑手套、蓝外套。',
    },
    {
        id: 'firefly', zh: '流萤', en: 'Firefly', jp: 'ホタル', series: '崩坏：星穹铁道', seriesTag: 'honkai: star rail',
        booru: 'firefly (honkai: star rail)', rating: 'sfw',
        aliases: ['流萤', 'firefly', '萨姆', 'sam'],
        identity: 'grey hair, long hair, gradient hair, multicolored hair, violet eyes, hair between eyes, gradient hair',
        outfitName: '标志性服装·流萤',
        outfit: 'black hairband, white shirt, sailor collar, school uniform, bowtie, pleated skirt, thigh-highs, bow, long sleeves',
        note: '灰发发梢渐变+紫瞳+黑发箍；白衬衫水手领校服。',
    },
    {
        id: 'sparkle', zh: '花火', en: 'Sparkle', jp: '花火', series: '崩坏：星穹铁道', seriesTag: 'honkai: star rail',
        booru: 'sparkle (honkai: star rail)', rating: 'sfw',
        aliases: ['花火', 'sparkle', '欢愉', '假面愚者'],
        identity: 'white hair, grey hair, long hair, twintails, pink eyes, heart facial mark, facial mark, bare shoulders',
        outfitName: '标志性服装·花火',
        outfit: 'black choker, hat, eyewear on head, long sleeves, gloves, skirt, hair ornament',
        note: '白发双马尾+粉瞳+脸颊心形印记+眼镜架在头上。',
    },
    {
        id: 'kafka', zh: '卡芙卡', en: 'Kafka', jp: 'カフカ', series: '崩坏：星穹铁道', seriesTag: 'honkai: star rail',
        booru: 'kafka (honkai: star rail)', rating: 'sfw',
        aliases: ['卡芙卡', 'kafka', '星核猎手', '母亲'],
        identity: 'purple hair, long hair, violet eyes, hair between eyes, ponytail',
        outfitName: '标志性服装·卡芙卡',
        outfit: 'white shirt, black jacket, round eyewear, sunglasses, eyewear on head, purple gloves, collared shirt, jewelry, jacket on shoulders',
        note: '紫发紫瞳+圆墨镜架在头顶+黑外套披肩+紫手套。',
    },
    {
        id: 'hakurei_reimu', zh: '博丽灵梦', en: 'Hakurei Reimu', jp: '博麗霊夢', series: '东方Project', seriesTag: 'touhou',
        booru: 'hakurei reimu', rating: 'sfw',
        aliases: ['博丽灵梦', '灵梦', 'reimu', 'hakurei reimu', '红白', '赤色杀人魔'],
        identity: 'brown hair, long hair, frilled hair tubes, hair tubes, brown eyes, hair bow',
        outfitName: '标志性服装·灵梦',
        outfit: 'red bow, frilled bow, red skirt, detached sleeves, ribbon-trimmed sleeves, yellow ascot, vest, frills, skirt set',
        note: '棕发+大红色发结+发管（hair tubes）+黄领巾+红裙+分离袖。',
    },
    {
        id: 'kirisame_marisa', zh: '雾雨魔理沙', en: 'Kirisame Marisa', jp: '霧雨魔理沙', series: '东方Project', seriesTag: 'touhou',
        booru: 'kirisame marisa', rating: 'sfw',
        aliases: ['雾雨魔理沙', '魔理沙', 'marisa', 'kirisame marisa', '黑白', '普通的魔法使'],
        identity: 'blonde hair, long hair, single braid, side braid, yellow eyes, hair bow',
        outfitName: '标志性服装·魔理沙',
        outfit: 'black witch hat, hat bow, white bow, black vest, white apron, waist apron, black skirt, puffy sleeves, frills',
        note: '金发单侧麻花辫+大黑女巫帽（白蝴蝶结）+黑马甲白围裙。',
    },
    {
        id: 'flandre_scarlet', zh: '芙兰朵露', en: 'Flandre Scarlet', jp: 'フランドール・スカーレット', series: '东方Project', seriesTag: 'touhou',
        booru: 'flandre scarlet', rating: 'sfw',
        aliases: ['芙兰朵露', '芙兰', 'flandre', 'flandre scarlet', '妹样', '恶魔之妹'],
        identity: 'blonde hair, one side up, red eyes, crystal wings, multicolored wings, wings',
        outfitName: '标志性服装·芙兰朵露',
        outfit: 'white mob cap, red vest, red skirt, yellow ascot, puffy short sleeves, frills, bow, white shirt',
        note: '金发侧束+红瞳+水晶翅膀（多色）+白帽+红马甲红裙。',
    },
    {
        id: 'izayoi_sakuya', zh: '十六夜咲夜', en: 'Izayoi Sakuya', jp: '十六夜咲夜', series: '东方Project', seriesTag: 'touhou',
        booru: 'izayoi sakuya', rating: 'sfw',
        aliases: ['十六夜咲夜', '咲夜', 'sakuya', 'izayoi sakuya', '女仆长', 'pad长'],
        identity: 'grey hair, long hair, twin braids, braid, hair bow, blue eyes',
        outfitName: '标志性服装·咲夜',
        outfit: 'maid headdress, blue dress, white apron, waist apron, green bow, pinafore dress, collared shirt, white shirt, sleeveless dress',
        note: '银灰双麻花辫+女仆头饰+蓝裙白围裙+绿蝴蝶结。',
    },
    {
        id: 'artoria_pendragon', zh: '阿尔托莉雅', en: 'Artoria Pendragon', jp: 'アルトリア・ペンドラゴン', series: 'Fate', seriesTag: 'fate (series)',
        booru: 'artoria pendragon (fate)', rating: 'sfw',
        aliases: ['阿尔托莉雅', 'saber', 'artoria', 'artoria pendragon', '呆毛王', '亚瑟王', '阿尔托莉雅·潘德拉贡'],
        identity: 'blonde hair, ahoge, green eyes, hair bun, braided base, bun with braided base, sidelocks',
        outfitName: '标志性服装·阿尔托莉雅',
        outfit: 'blue dress, armor, gauntlets, ribbon, hair ribbon, long sleeves, skirt',
        note: '金发盘发（编发底座）+呆毛+绿瞳；蓝裙+铠甲。',
    },
    {
        id: 'tohsaka_rin', zh: '远坂凛', en: 'Tohsaka Rin', jp: '遠坂凛', series: 'Fate', seriesTag: 'fate (series)',
        booru: 'tohsaka rin', rating: 'sfw',
        aliases: ['远坂凛', '凛', 'rin', 'tohsaka rin', '远坂', '红恶魔'],
        identity: 'black hair, long hair, twintails, two side up, blue eyes',
        outfitName: '标志性服装·凛',
        outfit: 'red jacket, black shirt, black thighhighs, skirt, ribbon, jewelry, earrings, gloves',
        note: '黑发双马尾（两侧束起）+蓝瞳+黑发带；红外套黑内搭黑丝。',
    },
    {
        id: 'mash_kyrielight', zh: '玛修', en: 'Mash Kyrielight', jp: 'マシュ・キリエライト', series: 'Fate', seriesTag: 'fate (series)',
        booru: 'mash kyrielight', rating: 'sfw',
        aliases: ['玛修', 'mash', 'mash kyrielight', '学妹', '玛修·基列莱特', '盾兵'],
        identity: 'pink hair, short hair, hair over one eye, violet eyes, ahoge, glasses',
        outfitName: '标志性服装·玛修',
        outfit: 'red necktie, white shirt, black skirt, jacket, long sleeves, ribbon, glasses',
        note: '粉短发（盖住一只眼）+紫瞳+眼镜+红领带。',
    },
    {
        id: 'jeanne_darc', zh: '贞德', en: "Jeanne d'Arc", jp: 'ジャンヌ・ダルク', series: 'Fate', seriesTag: 'fate (series)',
        booru: "jeanne d'arc (fate)", rating: 'sfw',
        aliases: ['贞德', 'jeanne', "jeanne d'arc", '白贞', '圣女', '圣女贞德'],
        identity: 'blonde hair, long hair, single braid, braid, blue eyes, yellow eyes, headpiece, ahoge',
        outfitName: '标志性服装·贞德',
        outfit: 'armor, gauntlets, white shirt, dress, long sleeves, hair between eyes, bow',
        note: '金长辫+蓝瞳+银白头饰+铠甲臂甲。',
    },
    {
        id: 'special_week', zh: '特别周', en: 'Special Week', jp: 'スペシャルウィーク', series: '赛马娘', seriesTag: 'umamusume',
        booru: 'special week (umamusume)', rating: 'sfw',
        aliases: ['特别周', 'special week', 'specialweek', '斯佩', '小特'],
        identity: 'brown hair, white hair, two-tone hair, multicolored hair, short hair, horse ears, animal ears, horse tail, violet eyes',
        outfitName: '标志性服装·特别周',
        outfit: 'purple bow, ear bow, half up braid, braid, shirt, short sleeves, skirt, jacket, ribbon',
        note: '棕白双色短发+马耳马尾+紫蝴蝶结（耳朵上）+半扎辫。',
    },
    {
        id: 'tokai_teio', zh: '东海帝王', en: 'Tokai Teio', jp: 'トウカイテイオー', series: '赛马娘', seriesTag: 'umamusume',
        booru: 'tokai teio', rating: 'sfw',
        aliases: ['东海帝王', '帝王', 'tokai teio', 'teio', '帝王大人'],
        identity: 'brown hair, streaked hair, white hair, multicolored hair, long hair, high ponytail, horse ears, horse tail, blue eyes',
        outfitName: '标志性服装·帝王',
        outfit: 'white skirt, pleated skirt, epaulettes, gloves, ribbon, school uniform, long sleeves',
        note: '棕发挑白+高马尾+马耳马尾+蓝瞳；白裙+肩章。',
    },
    {
        id: 'gold_ship', zh: '黄金船', en: 'Gold Ship', jp: 'ゴールドシップ', series: '赛马娘', seriesTag: 'umamusume',
        booru: 'gold ship (umamusume)', rating: 'sfw',
        aliases: ['黄金船', 'gold ship', 'goldship', 'ゴルシ'],
        identity: 'grey hair, long hair, blunt bangs, horse ears, animal ears, horse tail, violet eyes',
        outfitName: '标志性服装·黄金船',
        outfit: 'brown pillbox hat, pillbox hat, ear bow, red dress, sleeveless dress, white gloves, armband, bow',
        note: '灰长发齐刘海+马耳马尾+紫瞳；棕色圆筒帽+红无袖裙+白手套。',
    },
    {
        id: 'mejiro_mcqueen', zh: '目白麦昆', en: 'Mejiro McQueen', jp: 'メジロマックイーン', series: '赛马娘', seriesTag: 'umamusume',
        booru: 'mejiro mcqueen', rating: 'sfw',
        aliases: ['目白麦昆', '麦昆', 'mejiro mcqueen', 'mcqueen', '大小姐'],
        identity: 'purple hair, long hair, swept bangs, horse ears, animal ears, horse tail, violet eyes, eyebrows visible through hair',
        outfitName: '标志性服装·麦昆',
        outfit: 'school uniform, pleated skirt, ear ribbon, ribbon, bow, shirt, long sleeves, frills',
        note: '紫长发斜刘海+马耳马尾+紫瞳；学院制服+耳侧丝带。',
    },
    {
        id: 'jean', zh: '琴', en: 'Jean', jp: 'ジン', series: '原神', seriesTag: 'genshin impact',
        booru: 'jean (genshin impact)', rating: 'sfw',
        aliases: ['琴', 'jean', '琴团长', '蒲公英骑士', '代理团长'],
        identity: 'blonde hair, long hair, ponytail, blue eyes, hair between eyes, hair bow',
        outfitName: '标志性服装·琴',
        outfit: 'white dress, capelet, blue cape, gloves, knight uniform, hair bow, boots, long sleeves',
        note: '金发高马尾+蓝瞳+白色骑士制服+披肩。',
    },
    {
        id: 'sucrose', zh: '砂糖', en: 'Sucrose', jp: 'スクロース', series: '原神', seriesTag: 'genshin impact',
        booru: 'sucrose (genshin impact)', rating: 'sfw',
        aliases: ['砂糖', 'sucrose', '阿贝多的助手', '炼金术士'],
        identity: 'green hair, long hair, yellow eyes, semi-rimless eyewear, glasses, animal ears, animal ear fluff',
        outfitName: '标志性服装·砂糖',
        outfit: 'white hat, white gloves, dress, thigh-highs, long sleeves, hat',
        note: '绿发+半框眼镜+兽耳+白帽白手套。',
    },
    {
        id: 'noelle', zh: '诺艾尔', en: 'Noelle', jp: 'ノエル', series: '原神', seriesTag: 'genshin impact',
        booru: 'noelle (genshin impact)', rating: 'sfw',
        aliases: ['诺艾尔', 'noelle', '女仆', '西风骑士团女仆'],
        identity: 'grey hair, short hair, braid, green eyes, rose hair ornament, red rose, hair flower',
        outfitName: '标志性服装·诺艾尔',
        outfit: 'maid headdress, armor, white dress, gloves, long sleeves, hair flower',
        note: '银灰短发+绿瞳+红玫瑰发饰+女仆头饰+铠甲。',
    },
    {
        id: 'ningguang', zh: '凝光', en: 'Ningguang', jp: '凝光', series: '原神', seriesTag: 'genshin impact',
        booru: 'ningguang (genshin impact)', rating: 'sfw',
        aliases: ['凝光', 'ningguang', '天权星', '璃月七星', '富婆'],
        identity: 'white hair, very long hair, red eyes, hair stick, tassel hair ornament, hair ornament',
        outfitName: '标志性服装·凝光',
        outfit: 'chinese clothes, black gloves, jewelry, long sleeves, tassel, dress, hair stick, gold trim',
        note: '白发超长+红瞳+发簪+中式旗袍式礼服+黑长手套。',
    },
    {
        id: 'lisa', zh: '丽莎', en: 'Lisa', jp: 'リサ', series: '原神', seriesTag: 'genshin impact',
        booru: 'lisa (genshin impact)', rating: 'sfw',
        aliases: ['丽莎', 'lisa', '图书管理员', '蔷薇魔女'],
        identity: 'brown hair, long hair, side ponytail, ponytail, green eyes, hair between eyes',
        outfitName: '标志性服装·丽莎',
        outfit: 'purple witch hat, purple dress, gloves, flower, hair ornament, long sleeves',
        note: '棕发侧马尾+绿瞳+紫女巫帽与紫裙。',
    },
    {
        id: 'beidou', zh: '北斗', en: 'Beidou', jp: '北斗', series: '原神', seriesTag: 'genshin impact',
        booru: 'beidou (genshin impact)', rating: 'sfw',
        aliases: ['北斗', 'beidou', '南十字', '船长', '大姐头'],
        identity: 'brown hair, long hair, red eyes, eyepatch, hair between eyes',
        outfitName: '标志性服装·北斗',
        outfit: 'red dress, fingerless gloves, jewelry, earrings, long sleeves, thighhighs, chinese clothes',
        note: '棕发红瞳+**左眼眼罩**（最强辨识点）+露指手套。',
    },
    {
        id: 'fischl', zh: '菲谢尔', en: 'Fischl', jp: 'フィッシュル', series: '原神', seriesTag: 'genshin impact',
        booru: 'fischl (genshin impact)', rating: 'sfw',
        aliases: ['菲谢尔', 'fischl', '皇女', '奥兹', '断罪之皇女'],
        identity: 'blonde hair, long hair, twintails, two side up, green eyes, eyepatch, hair over one eye',
        outfitName: '标志性服装·菲谢尔',
        outfit: 'purple dress, detached sleeves, thigh-highs, black gloves, ribbon, bare shoulders, boots',
        note: '金发双马尾+绿瞳+**眼罩**+紫黑礼服。',
    },
    {
        id: 'kujou_sara', zh: '九条裟罗', en: 'Kujou Sara', jp: '九条裟羅', series: '原神', seriesTag: 'genshin impact',
        booru: 'kujou sara', rating: 'sfw',
        aliases: ['九条裟罗', '九条', '裟罗', 'kujou sara', 'sara', '天狗'],
        identity: 'black hair, purple hair, short hair, yellow eyes, violet eyes, hair ornament',
        outfitName: '标志性服装·裟罗',
        outfit: 'tengu mask, mask on head, japanese clothes, detached sleeves, gloves, long sleeves',
        note: '黑紫短发+金瞳+**天狗面具架在头上**+和风装束。',
    },
    {
        id: 'kuki_shinobu', zh: '久岐忍', en: 'Kuki Shinobu', jp: '久岐忍', series: '原神', seriesTag: 'genshin impact',
        booru: 'kuki shinobu', rating: 'sfw',
        aliases: ['久岐忍', '忍', 'kuki shinobu', 'shinobu', '荒泷派', '阿忍'],
        identity: 'green hair, long hair, violet eyes, hair between eyes, mask, mouth mask, hair ornament',
        outfitName: '标志性服装·久岐忍',
        outfit: 'black jacket, japanese clothes, black gloves, long sleeves, shorts, hair ornament',
        note: '绿发紫瞳+**遮口面罩**+黑外套。',
    },
    {
        id: 'dori', zh: '多莉', en: 'Dori', jp: 'ドリー', series: '原神', seriesTag: 'genshin impact',
        booru: 'dori (genshin impact)', rating: 'sfw',
        aliases: ['多莉', 'dori', '商人', '多莉大人', '桑歌玛哈'],
        identity: 'pink hair, long hair, ahoge, yellow eyes, multicolored hair, hair between eyes',
        outfitName: '标志性服装·多莉',
        outfit: 'hat, tinted eyewear, detached sleeves, jewelry, gloves, long sleeves, dress, hair ornament',
        note: '粉发+黄瞳+呆毛+墨镜片+大帽子和一堆首饰（商人造型）。',
    },
    {
        id: 'nahida', zh: '纳西妲', en: 'Nahida', jp: 'ナヒーダ', series: '原神', seriesTag: 'genshin impact',
        booru: 'nahida (genshin impact)', rating: 'sfw', minor: true,
        aliases: ['纳西妲', 'nahida', '草神', '小吉祥草王', '布耶尔'],
        identity: 'white hair, green hair, long hair, multicolored hair, cross-shaped pupils, symbol-shaped pupils, green eyes, pointy ears, side ponytail',
        outfitName: '标志性服装·纳西妲',
        outfit: 'white dress, leaf hair ornament, hat, long sleeves, braid, hair ornament',
        note: '白发挑绿+**十字形瞳孔**+尖耳+侧马尾+白色草神装（幼态角色，已标记 minor）。',
    },
    {
        id: 'collei', zh: '柯莱', en: 'Collei', jp: 'コレイ', series: '原神', seriesTag: 'genshin impact',
        booru: 'collei (genshin impact)', rating: 'sfw',
        aliases: ['柯莱', 'collei', '森林巡逻员', '须弥'],
        identity: 'green hair, long hair, violet eyes, ahoge, hair between eyes, hair ornament',
        outfitName: '标志性服装·柯莱',
        outfit: 'green capelet, cape, white dress, long sleeves, earrings, jewelry, boots',
        note: '绿发+紫瞳+呆毛+绿色小披肩。',
    },
    {
        id: 'nilou', zh: '妮露', en: 'Nilou', jp: 'ニィロウ', series: '原神', seriesTag: 'genshin impact',
        booru: 'nilou (genshin impact)', rating: 'sfw',
        aliases: ['妮露', 'nilou', '舞者', '祖拜尔剧场'],
        identity: 'red hair, very long hair, aqua eyes, twintails, fake horns, horns, hair ornament',
        outfitName: '标志性服装·妮露',
        outfit: 'white veil, veil, harem outfit, detached sleeves, jewelry, circlet, long sleeves, bare shoulders',
        note: '红发超长+水色瞳+假角+**白色头纱**+舞娘装。',
    },
    {
        id: 'barbara', zh: '芭芭拉', en: 'Barbara', jp: 'バーバラ', series: '原神', seriesTag: 'genshin impact',
        booru: 'barbara (genshin impact)', rating: 'sfw',
        aliases: ['芭芭拉', 'barbara', '偶像', '西风教会', '祈礼牧师'],
        identity: 'blonde hair, long hair, twintails, twin drills, drill hair, blue eyes',
        outfitName: '标志性服装·芭芭拉',
        outfit: 'white dress, detached sleeves, bow, hair ornament, long sleeves, hat',
        note: '金发双钻卷+蓝瞳+白蓝偶像裙。',
    },
    {
        id: 'yelan', zh: '夜兰', en: 'Yelan', jp: '夜蘭', series: '原神', seriesTag: 'genshin impact',
        booru: 'yelan (genshin impact)', rating: 'sfw',
        aliases: ['夜兰', 'yelan', '情报官', '璃月谍报', '夜阑'],
        identity: 'blue hair, black hair, short hair, green eyes, diagonal bangs, hair between eyes',
        outfitName: '标志性服装·夜兰',
        outfit: 'black gloves, jacket, jewelry, dress, long sleeves, fur trim',
        note: '墨蓝短发+绿瞳+斜刘海+黑长手套。',
    },
    {
        id: 'amber', zh: '安柏', en: 'Amber', jp: 'アンバー', series: '原神', seriesTag: 'genshin impact',
        booru: 'amber (genshin impact)', rating: 'sfw',
        aliases: ['安柏', 'amber', '侦察骑士', '兔兔伯爵'],
        identity: 'brown hair, long hair, hair between eyes, goggles',
        outfitName: '标志性服装·安柏',
        outfit: 'red jacket, red ribbon, hair ribbon, gloves, shorts, thigh-highs, goggles, long sleeves',
        note: '棕发+**红发带**+护目镜架在头上+红短外套短裤。',
    },
    {
        id: 'klee', zh: '可莉', en: 'Klee', jp: 'クレー', series: '原神', seriesTag: 'genshin impact',
        booru: 'klee (genshin impact)', rating: 'sfw', minor: true,
        aliases: ['可莉', 'klee', '火花骑士', '蒙德爆炸犯'],
        identity: 'blonde hair, long hair, low twintails, red eyes, pointy ears, ahoge, hair between eyes',
        outfitName: '标志性服装·可莉',
        outfit: 'red hat, dress, gloves, long sleeves, shirt, boots',
        note: '金发低双马尾+红瞳+尖耳+**红色贝雷帽**（幼态角色，已标记 minor）。',
    },
    {
        id: 'yanfei', zh: '烟绯', en: 'Yanfei', jp: '煙緋', series: '原神', seriesTag: 'genshin impact',
        booru: 'yanfei (genshin impact)', rating: 'sfw',
        aliases: ['烟绯', 'yanfei', '律师', '半仙', '法典'],
        identity: 'pink hair, long hair, antlers, horns, green eyes, hair between eyes',
        outfitName: '标志性服装·烟绯',
        outfit: 'red hat, shirt, long sleeves, detached sleeves, chinese clothes, gloves',
        note: '粉发+**鹿角**+绿瞳+红帽子（律师造型）。',
    },
    {
        id: 'shenhe', zh: '申鹤', en: 'Shenhe', jp: '申鶴', series: '原神', seriesTag: 'genshin impact',
        booru: 'shenhe (genshin impact)', rating: 'sfw',
        aliases: ['申鹤', 'shenhe', '仙鹤', '留云借风', '徒弟'],
        identity: 'white hair, grey hair, long hair, hair over one eye, blue eyes, braid',
        outfitName: '标志性服装·申鹤',
        outfit: 'blue dress, chinese clothes, tassel, gloves, jewelry, long sleeves, clothing cutout',
        note: '白发（盖住一只眼）+蓝瞳+流苏耳坠+蓝白中式装。',
    },
    {
        id: 'rosaria', zh: '罗莎莉亚', en: 'Rosaria', jp: 'ロサリア', series: '原神', seriesTag: 'genshin impact',
        booru: 'rosaria (genshin impact)', rating: 'sfw',
        aliases: ['罗莎莉亚', 'rosaria', '修女', '西风教会'],
        identity: 'purple hair, multicolored hair, long hair, red eyes, hair between eyes',
        outfitName: '标志性服装·罗莎莉亚',
        outfit: 'nun, black dress, gloves, hat, long sleeves, veil',
        note: '紫发红瞳+修女装+头纱。',
    },
    {
        id: 'arlecchino', zh: '阿蕾奇诺', en: 'Arlecchino', jp: 'アルレッキーノ', series: '原神', seriesTag: 'genshin impact',
        booru: 'arlecchino (genshin impact)', rating: 'sfw',
        aliases: ['阿蕾奇诺', 'arlecchino', '仆人', '愚人众', '父亲'],
        identity: 'white hair, black hair, streaked hair, two-tone hair, long hair, x-shaped pupils, red pupils, black eyes, black hands',
        outfitName: '标志性服装·阿蕾奇诺',
        outfit: 'black coat, white shirt, long sleeves, gloves, ascot, dress',
        note: '黑白双色发+**X 形红瞳**+黑手（手套）+黑外套。',
    },
    {
        id: 'mavuika', zh: '玛薇卡', en: 'Mavuika', jp: 'マヴィカ', series: '原神', seriesTag: 'genshin impact',
        booru: 'mavuika (genshin impact)', rating: 'sfw',
        aliases: ['玛薇卡', 'mavuika', '火神', '纳塔', '太阳'],
        identity: 'red hair, orange hair, multicolored hair, long hair, ahoge, orange eyes',
        outfitName: '标志性服装·玛薇卡',
        outfit: 'black gloves, dress, jewelry, earrings, long sleeves, boots',
        note: '红橙渐变长发+呆毛+黑手套（火神造型）。',
    },
    {
        id: 'sigewinne', zh: '希格雯', en: 'Sigewinne', jp: 'シグウィン', series: '原神', seriesTag: 'genshin impact',
        booru: 'sigewinne (genshin impact)', rating: 'sfw',
        aliases: ['希格雯', 'sigewinne', '护士长', '梅洛彼得堡'],
        identity: 'blue hair, long hair, low twintails, multicolored hair, red eyes, hair between eyes',
        outfitName: '标志性服装·希格雯',
        outfit: 'nurse cap, white hat, white gloves, red bow, bowtie, long sleeves, dress',
        note: '蓝发低双马尾+红瞳+**护士帽**+红蝴蝶结白手套。',
    },
    {
        id: 'clorinde', zh: '克洛琳德', en: 'Clorinde', jp: 'クロリンデ', series: '原神', seriesTag: 'genshin impact',
        booru: 'clorinde (genshin impact)', rating: 'sfw',
        aliases: ['克洛琳德', 'clorinde', '决斗代理人', '枫丹'],
        identity: 'blue hair, purple hair, long hair, violet eyes, hair between eyes',
        outfitName: '标志性服装·克洛琳德',
        outfit: 'hat, white shirt, white gloves, ascot, corset, dress, long sleeves',
        note: '蓝紫发+紫瞳+帽子+白衬衫领巾束腰。',
    },
    {
        id: 'candace', zh: '坎蒂丝', en: 'Candace', jp: 'キャンディス', series: '原神', seriesTag: 'genshin impact',
        booru: 'candace (genshin impact)', rating: 'sfw',
        aliases: ['坎蒂丝', 'candace', '守卫', '阿如村', '沙漠'],
        identity: 'dark skin, blue hair, long hair, short hair with long locks, heterochromia, blue eyes, yellow eyes, multicolored hair, hair between eyes',
        outfitName: '标志性服装·坎蒂丝',
        outfit: 'white dress, jewelry, hair ornament, headpiece, bare shoulders, gold trim, sandals',
        note: '深肤色+蓝发+**异色瞳（蓝/金）**+金色首饰与头饰。',
    },
    {
        id: 'diona', zh: '迪奥娜', en: 'Diona', jp: 'ディオナ', series: '原神', seriesTag: 'genshin impact',
        booru: 'diona (genshin impact)', rating: 'sfw', minor: true,
        aliases: ['迪奥娜', 'diona', '猫尾酒保', '冰猫'],
        identity: 'pink hair, short hair, cat ears, animal ears, animal ear fluff, cat tail, green eyes, bangs pinned back',
        outfitName: '标志性服装·迪奥娜',
        outfit: 'hat, gloves, long sleeves, shorts, detached sleeves, boots',
        note: '粉发+猫耳猫尾+绿瞳+帽子短裤（幼态角色，已标记 minor）。',
    },
    {
        id: 'charlotte', zh: '夏洛蒂', en: 'Charlotte', jp: 'シャルロット', series: '原神', seriesTag: 'genshin impact',
        booru: 'charlotte (genshin impact)', rating: 'sfw',
        aliases: ['夏洛蒂', 'charlotte', '记者', '蒸汽鸟报'],
        identity: 'pink hair, short hair, aqua eyes, monocle',
        outfitName: '标志性服装·夏洛蒂',
        outfit: 'red hat, newsboy cap, white gloves, detached sleeves, long sleeves, shirt, bow, camera',
        note: '粉发短发+水色瞳+**单片眼镜**+红色记者帽+相机。',
    },
    {
        id: 'lynette', zh: '琳妮特', en: 'Lynette', jp: 'リネット', series: '原神', seriesTag: 'genshin impact',
        booru: 'lynette (genshin impact)', rating: 'sfw',
        aliases: ['琳妮特', 'lynette', '魔术助手', '猫猫'],
        identity: 'grey hair, short hair, cat ears, animal ears, animal ear fluff, violet eyes, star facial mark, facial mark',
        outfitName: '标志性服装·琳妮特',
        outfit: 'black dress, white dress, bow, long sleeves, gloves, black gloves, hat',
        note: '灰发+猫耳+紫瞳+**星星脸纹**+黑白女仆风魔术装。',
    },
    {
        id: 'faruzan', zh: '珐露珊', en: 'Faruzan', jp: 'ファルザン', series: '原神', seriesTag: 'genshin impact',
        booru: 'faruzan (genshin impact)', rating: 'sfw',
        aliases: ['珐露珊', 'faruzan', '百年前辈', '风论派'],
        identity: 'aqua hair, long hair, twintails, green eyes, triangle-shaped pupils, symbol-shaped pupils, cowlick',
        outfitName: '标志性服装·珐露珊',
        outfit: 'white dress, x hair ornament, hair ornament, jewelry, bracelet, shoulder cutout, clothing cutout, short sleeves',
        note: '水色长发双马尾+绿瞳+**三角形瞳孔**+X 形发饰+白裙。',
    },
    {
        id: 'kachina', zh: '卡齐娜', en: 'Kachina', jp: 'カチーナ', series: '原神', seriesTag: 'genshin impact',
        booru: 'kachina (genshin impact)', rating: 'sfw', minor: true,
        aliases: ['卡齐娜', 'kachina', '纳塔', '小卡齐娜'],
        identity: 'brown hair, long hair, braid, animal ears, blue eyes, headband',
        outfitName: '标志性服装·卡齐娜',
        outfit: 'visor cap, gloves, mittens, jewelry, boots, headband',
        note: '棕发辫子+兽耳+蓝瞳+遮阳帽+连指手套（幼态角色，已标记 minor）。',
    },
    {
        id: 'xilonen', zh: '希诺宁', en: 'Xilonen', jp: 'シロネン', series: '原神', seriesTag: 'genshin impact',
        booru: 'xilonen (genshin impact)', rating: 'sfw',
        aliases: ['希诺宁', 'xilonen', '锻造师', '纳塔', 'DJ'],
        identity: 'blonde hair, multicolored hair, long hair, braid, jaguar ears, animal ears, jaguar tail, green eyes, jaguar girl',
        outfitName: '标志性服装·希诺宁',
        outfit: 'jacket, gloves, jewelry, long sleeves, boots, belt',
        note: '金发+**豹耳豹尾**+绿瞳+夹克与一堆金属首饰（锻造师）。',
    },
    {
        id: 'mualani', zh: '玛拉妮', en: 'Mualani', jp: 'ムアラニ', series: '原神', seriesTag: 'genshin impact',
        booru: 'mualani (genshin impact)', rating: 'sfw',
        aliases: ['玛拉妮', 'mualani', '向导', '纳塔', '冲浪'],
        identity: 'blue hair, white hair, multicolored hair, long hair, twin braids, braid, red eyes, dark skin',
        outfitName: '标志性服装·玛拉妮',
        outfit: 'blue hairband, hairband, fingerless gloves, swimsuit, shorts, jewelry, sandals',
        note: '蓝白双辫+红瞳+蓝发箍+深肤色+露指手套。',
    },
    {
        id: 'citlali', zh: '茜特菈莉', en: 'Citlali', jp: 'シトラリ', series: '原神', seriesTag: 'genshin impact',
        booru: 'citlali (genshin impact)', rating: 'sfw',
        aliases: ['茜特菈莉', 'citlali', '奶奶', '占星', '纳塔'],
        identity: 'pink hair, long hair, braid, blue eyes, pink pupils, triangle facial mark, facial mark, forehead mark, bare shoulders',
        outfitName: '标志性服装·茜特菈莉',
        outfit: 'sleep mask, mask on head, dress, hair ornament, jewelry, bare shoulders, sandals',
        note: '粉长发+蓝瞳+**三角脸纹与额纹**+睡眠眼罩架在头上+露肩。',
    },
    {
        id: 'chasca', zh: '恰斯卡', en: 'Chasca', jp: 'チャスカ', series: '原神', seriesTag: 'genshin impact',
        booru: 'chasca (genshin impact)', rating: 'sfw',
        aliases: ['恰斯卡', 'chasca', '纳塔', '和平使者'],
        identity: 'red hair, blonde hair, multicolored hair, long hair, braid, pointy ears, blue eyes',
        outfitName: '标志性服装·恰斯卡',
        outfit: 'hat, scarf, black gloves, jewelry, gloves, long sleeves, boots',
        note: '红金多色长发+尖耳+蓝瞳+帽子围巾黑手套。',
    },
    {
        id: 'sayu', zh: '早柚', en: 'Sayu', jp: '早柚', series: '原神', seriesTag: 'genshin impact',
        booru: 'sayu (genshin impact)', rating: 'sfw', minor: true,
        aliases: ['早柚', 'sayu', '忍者', '小狸猫', '社奉行'],
        identity: 'grey hair, blonde hair, long hair, blunt bangs, animal ears, animal ear fluff, tail, violet eyes, leaf on head',
        outfitName: '标志性服装·早柚',
        outfit: 'animal hood, hood, japanese clothes, black gloves, fingerless gloves, leaf, boots',
        note: '灰金发+兽耳尾巴+紫瞳+**头顶叶子**+动物兜帽忍者装（幼态角色，已标记 minor）。',
    },
];

/** 系列列表（面板的系列筛选下拉用）。 */
export const FANCHAR_SERIES = [...new Set(FANCHARS.map(c => c.series))];

/** 把一条角色记录拼成插件用的身份串：booru tag + 作品 tag + 外观 tag。 */
export function fanIdentityTags(c) {
    return [c.booru, c.seriesTag, c.identity].filter(Boolean).join(', ');
}
